spring:
  datasource:
    url: jdbc:sqlserver://militairydb.database.windows.net:1433;database=zipcode_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: youssef
    password: Militaire@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect