package com.datajpa.relationship.model;

public enum ERole {
  ROLE_ADMIN,
  ROLE_USER,
  ROLE_ACCEUIL,
  ROLE_ATTENTE,
  ROLE_SERVICECONSULTATION,
  ROLE_PAIEMENT,
  ROLE_CONFIGURATION,
  ROLE_PRISERDV,
  ROLE_CONSULTANT,
  Role_DASHBORD,


}
